# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('expose', ['dcep', 'stream-processing', 'netanim', 'mobility', 'wifi', 'stats', 'csma', 'internet', 'network', 'olsr', 'point-to-point'])
    obj.source = 'expose.cc'
