# CMake generated Testfile for 
# Source directory: /home/espen/ns-3/ns3-wip/src/spectrum/examples
# Build directory: /home/espen/ns-3/ns3-wip/cmake-cache/src/spectrum/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[ctest-adhoc-aloha-ideal-phy]=] "ns3.36.1-adhoc-aloha-ideal-phy-debug")
set_tests_properties([=[ctest-adhoc-aloha-ideal-phy]=] PROPERTIES  WORKING_DIRECTORY "/home/espen/ns-3/ns3-wip/build/src/spectrum/examples/" _BACKTRACE_TRIPLES "/home/espen/ns-3/ns3-wip/build-support/macros-and-definitions.cmake;1344;add_test;/home/espen/ns-3/ns3-wip/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/espen/ns-3/ns3-wip/src/spectrum/examples/CMakeLists.txt;1;build_lib_example;/home/espen/ns-3/ns3-wip/src/spectrum/examples/CMakeLists.txt;0;")
add_test([=[ctest-adhoc-aloha-ideal-phy-matrix-propagation-loss-model]=] "ns3.36.1-adhoc-aloha-ideal-phy-matrix-propagation-loss-model-debug")
set_tests_properties([=[ctest-adhoc-aloha-ideal-phy-matrix-propagation-loss-model]=] PROPERTIES  WORKING_DIRECTORY "/home/espen/ns-3/ns3-wip/build/src/spectrum/examples/" _BACKTRACE_TRIPLES "/home/espen/ns-3/ns3-wip/build-support/macros-and-definitions.cmake;1344;add_test;/home/espen/ns-3/ns3-wip/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/espen/ns-3/ns3-wip/src/spectrum/examples/CMakeLists.txt;11;build_lib_example;/home/espen/ns-3/ns3-wip/src/spectrum/examples/CMakeLists.txt;0;")
add_test([=[ctest-adhoc-aloha-ideal-phy-with-microwave-oven]=] "ns3.36.1-adhoc-aloha-ideal-phy-with-microwave-oven-debug")
set_tests_properties([=[ctest-adhoc-aloha-ideal-phy-with-microwave-oven]=] PROPERTIES  WORKING_DIRECTORY "/home/espen/ns-3/ns3-wip/build/src/spectrum/examples/" _BACKTRACE_TRIPLES "/home/espen/ns-3/ns3-wip/build-support/macros-and-definitions.cmake;1344;add_test;/home/espen/ns-3/ns3-wip/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/espen/ns-3/ns3-wip/src/spectrum/examples/CMakeLists.txt;21;build_lib_example;/home/espen/ns-3/ns3-wip/src/spectrum/examples/CMakeLists.txt;0;")
add_test([=[ctest-tv-trans-example]=] "ns3.36.1-tv-trans-example-debug")
set_tests_properties([=[ctest-tv-trans-example]=] PROPERTIES  WORKING_DIRECTORY "/home/espen/ns-3/ns3-wip/build/src/spectrum/examples/" _BACKTRACE_TRIPLES "/home/espen/ns-3/ns3-wip/build-support/macros-and-definitions.cmake;1344;add_test;/home/espen/ns-3/ns3-wip/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/espen/ns-3/ns3-wip/src/spectrum/examples/CMakeLists.txt;31;build_lib_example;/home/espen/ns-3/ns3-wip/src/spectrum/examples/CMakeLists.txt;0;")
add_test([=[ctest-tv-trans-regional-example]=] "ns3.36.1-tv-trans-regional-example-debug")
set_tests_properties([=[ctest-tv-trans-regional-example]=] PROPERTIES  WORKING_DIRECTORY "/home/espen/ns-3/ns3-wip/build/src/spectrum/examples/" _BACKTRACE_TRIPLES "/home/espen/ns-3/ns3-wip/build-support/macros-and-definitions.cmake;1344;add_test;/home/espen/ns-3/ns3-wip/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/espen/ns-3/ns3-wip/src/spectrum/examples/CMakeLists.txt;40;build_lib_example;/home/espen/ns-3/ns3-wip/src/spectrum/examples/CMakeLists.txt;0;")
add_test([=[ctest-three-gpp-channel-example]=] "ns3.36.1-three-gpp-channel-example-debug")
set_tests_properties([=[ctest-three-gpp-channel-example]=] PROPERTIES  WORKING_DIRECTORY "/home/espen/ns-3/ns3-wip/build/src/spectrum/examples/" _BACKTRACE_TRIPLES "/home/espen/ns-3/ns3-wip/build-support/macros-and-definitions.cmake;1344;add_test;/home/espen/ns-3/ns3-wip/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/espen/ns-3/ns3-wip/src/spectrum/examples/CMakeLists.txt;49;build_lib_example;/home/espen/ns-3/ns3-wip/src/spectrum/examples/CMakeLists.txt;0;")
