# CMake generated Testfile for 
# Source directory: /home/espen/ns-3/ns3-wip/examples/tutorial
# Build directory: /home/espen/ns-3/ns3-wip/cmake-cache/examples/tutorial
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[ctest-hello-simulator]=] "ns3.36.1-hello-simulator-debug")
set_tests_properties([=[ctest-hello-simulator]=] PROPERTIES  WORKING_DIRECTORY "/home/espen/ns-3/ns3-wip/build/examples/tutorial/" _BACKTRACE_TRIPLES "/home/espen/ns-3/ns3-wip/build-support/macros-and-definitions.cmake;1344;add_test;/home/espen/ns-3/ns3-wip/build-support/macros-and-definitions.cmake;1513;set_runtime_outputdirectory;/home/espen/ns-3/ns3-wip/examples/tutorial/CMakeLists.txt;1;build_example;/home/espen/ns-3/ns3-wip/examples/tutorial/CMakeLists.txt;0;")
add_test([=[ctest-first]=] "ns3.36.1-first-debug")
set_tests_properties([=[ctest-first]=] PROPERTIES  WORKING_DIRECTORY "/home/espen/ns-3/ns3-wip/build/examples/tutorial/" _BACKTRACE_TRIPLES "/home/espen/ns-3/ns3-wip/build-support/macros-and-definitions.cmake;1344;add_test;/home/espen/ns-3/ns3-wip/build-support/macros-and-definitions.cmake;1513;set_runtime_outputdirectory;/home/espen/ns-3/ns3-wip/examples/tutorial/CMakeLists.txt;7;build_example;/home/espen/ns-3/ns3-wip/examples/tutorial/CMakeLists.txt;0;")
add_test([=[ctest-second]=] "ns3.36.1-second-debug")
set_tests_properties([=[ctest-second]=] PROPERTIES  WORKING_DIRECTORY "/home/espen/ns-3/ns3-wip/build/examples/tutorial/" _BACKTRACE_TRIPLES "/home/espen/ns-3/ns3-wip/build-support/macros-and-definitions.cmake;1344;add_test;/home/espen/ns-3/ns3-wip/build-support/macros-and-definitions.cmake;1513;set_runtime_outputdirectory;/home/espen/ns-3/ns3-wip/examples/tutorial/CMakeLists.txt;17;build_example;/home/espen/ns-3/ns3-wip/examples/tutorial/CMakeLists.txt;0;")
add_test([=[ctest-third]=] "ns3.36.1-third-debug")
set_tests_properties([=[ctest-third]=] PROPERTIES  WORKING_DIRECTORY "/home/espen/ns-3/ns3-wip/build/examples/tutorial/" _BACKTRACE_TRIPLES "/home/espen/ns-3/ns3-wip/build-support/macros-and-definitions.cmake;1344;add_test;/home/espen/ns-3/ns3-wip/build-support/macros-and-definitions.cmake;1513;set_runtime_outputdirectory;/home/espen/ns-3/ns3-wip/examples/tutorial/CMakeLists.txt;28;build_example;/home/espen/ns-3/ns3-wip/examples/tutorial/CMakeLists.txt;0;")
add_test([=[ctest-fourth]=] "ns3.36.1-fourth-debug")
set_tests_properties([=[ctest-fourth]=] PROPERTIES  WORKING_DIRECTORY "/home/espen/ns-3/ns3-wip/build/examples/tutorial/" _BACKTRACE_TRIPLES "/home/espen/ns-3/ns3-wip/build-support/macros-and-definitions.cmake;1344;add_test;/home/espen/ns-3/ns3-wip/build-support/macros-and-definitions.cmake;1513;set_runtime_outputdirectory;/home/espen/ns-3/ns3-wip/examples/tutorial/CMakeLists.txt;40;build_example;/home/espen/ns-3/ns3-wip/examples/tutorial/CMakeLists.txt;0;")
add_test([=[ctest-fifth]=] "ns3.36.1-fifth-debug")
set_tests_properties([=[ctest-fifth]=] PROPERTIES  WORKING_DIRECTORY "/home/espen/ns-3/ns3-wip/build/examples/tutorial/" _BACKTRACE_TRIPLES "/home/espen/ns-3/ns3-wip/build-support/macros-and-definitions.cmake;1344;add_test;/home/espen/ns-3/ns3-wip/build-support/macros-and-definitions.cmake;1513;set_runtime_outputdirectory;/home/espen/ns-3/ns3-wip/examples/tutorial/CMakeLists.txt;46;build_example;/home/espen/ns-3/ns3-wip/examples/tutorial/CMakeLists.txt;0;")
add_test([=[ctest-sixth]=] "ns3.36.1-sixth-debug")
set_tests_properties([=[ctest-sixth]=] PROPERTIES  WORKING_DIRECTORY "/home/espen/ns-3/ns3-wip/build/examples/tutorial/" _BACKTRACE_TRIPLES "/home/espen/ns-3/ns3-wip/build-support/macros-and-definitions.cmake;1344;add_test;/home/espen/ns-3/ns3-wip/build-support/macros-and-definitions.cmake;1513;set_runtime_outputdirectory;/home/espen/ns-3/ns3-wip/examples/tutorial/CMakeLists.txt;57;build_example;/home/espen/ns-3/ns3-wip/examples/tutorial/CMakeLists.txt;0;")
add_test([=[ctest-seventh]=] "ns3.36.1-seventh-debug")
set_tests_properties([=[ctest-seventh]=] PROPERTIES  WORKING_DIRECTORY "/home/espen/ns-3/ns3-wip/build/examples/tutorial/" _BACKTRACE_TRIPLES "/home/espen/ns-3/ns3-wip/build-support/macros-and-definitions.cmake;1344;add_test;/home/espen/ns-3/ns3-wip/build-support/macros-and-definitions.cmake;1513;set_runtime_outputdirectory;/home/espen/ns-3/ns3-wip/examples/tutorial/CMakeLists.txt;68;build_example;/home/espen/ns-3/ns3-wip/examples/tutorial/CMakeLists.txt;0;")
