
window_jumps = [i*200 for i in range(15)]

for window_jump in window_jumps:
    print(f'nohup python3 ../ns3 run --no-build "lazy-migration-minimize-latency --yaml-config aggregation-test.yaml --experiment-id 4 --migration-mechanism no-migration --tuples-between-join 1 --joins-per-tuple 1 --join-range 1 --percentage-A-tuples-join 100 --window-jump {window_jump} --run-id 2_{window_jump} --batch-size 1000 --number-window-extents 100" > output/2_{window_jump}_no-migration.nohup 2>&1 &disown')
    print(f'nohup python3 ../ns3 run --no-build "lazy-migration-minimize-latency --yaml-config aggregation-test.yaml --experiment-id 4 --migration-mechanism all-at-once --tuples-between-join 1 --joins-per-tuple 1 --join-range 1 --percentage-A-tuples-join 100 --window-jump {window_jump} --run-id 2_{window_jump} --batch-size 1000 --number-window-extents 100" > output/2_{window_jump}_all-at-once.nohup 2>&1 &disown')
    print(f'nohup python3 ../ns3 run --no-build "lazy-migration-minimize-latency --yaml-config aggregation-test.yaml --experiment-id 4 --migration-mechanism rhino --tuples-between-join 1 --joins-per-tuple 1 --join-range 1 --percentage-A-tuples-join 100 --window-jump {window_jump} --run-id 2_{window_jump} --batch-size 1000 --number-window-extents 100" > output/2_{window_jump}_rhino.nohup 2>&1 &disown')
    print(f'nohup python3 ../ns3 run --no-build "lazy-migration-minimize-latency --yaml-config aggregation-test.yaml --experiment-id 4 --migration-mechanism meces --tuples-between-join 1 --joins-per-tuple 1 --join-range 1 --percentage-A-tuples-join 100 --window-jump {window_jump} --run-id 2_{window_jump} --batch-size 1000 --number-window-extents 100" > output/2_{window_jump}_meces.nohup 2>&1 &disown')
    print(f'nohup python3 ../ns3 run --no-build "lazy-migration-minimize-latency --yaml-config aggregation-test.yaml --experiment-id 4 --migration-mechanism megaphone --tuples-between-join 1 --joins-per-tuple 1 --join-range 1 --percentage-A-tuples-join 100 --window-jump {window_jump} --run-id 2_{window_jump} --batch-size 1000 --number-window-extents 100" > output/2_{window_jump}_megaphone.nohup 2>&1 &disown')
    print(f'nohup python3 ../ns3 run --no-build "lazy-migration-minimize-latency --yaml-config aggregation-test.yaml --experiment-id 4 --migration-mechanism lazy --tuples-between-join 1 --joins-per-tuple 1 --join-range 1 --percentage-A-tuples-join 100 --window-jump {window_jump} --run-id 2_{window_jump} --batch-size 1000 --number-window-extents 100" > output/2_{window_jump}_lazy.nohup 2>&1 &disown')
