# CMake generated Testfile for 
# Source directory: /home/espen/ns-3/ns3-wip/examples/routing
# Build directory: /home/espen/ns-3/ns3-wip/cmake-cache/examples/routing
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[ctest-dynamic-global-routing]=] "ns3.36.1-dynamic-global-routing-debug")
set_tests_properties([=[ctest-dynamic-global-routing]=] PROPERTIES  WORKING_DIRECTORY "/home/espen/ns-3/ns3-wip/build/examples/routing/" _BACKTRACE_TRIPLES "/home/espen/ns-3/ns3-wip/build-support/macros-and-definitions.cmake;1344;add_test;/home/espen/ns-3/ns3-wip/build-support/macros-and-definitions.cmake;1513;set_runtime_outputdirectory;/home/espen/ns-3/ns3-wip/examples/routing/CMakeLists.txt;1;build_example;/home/espen/ns-3/ns3-wip/examples/routing/CMakeLists.txt;0;")
add_test([=[ctest-static-routing-slash32]=] "ns3.36.1-static-routing-slash32-debug")
set_tests_properties([=[ctest-static-routing-slash32]=] PROPERTIES  WORKING_DIRECTORY "/home/espen/ns-3/ns3-wip/build/examples/routing/" _BACKTRACE_TRIPLES "/home/espen/ns-3/ns3-wip/build-support/macros-and-definitions.cmake;1344;add_test;/home/espen/ns-3/ns3-wip/build-support/macros-and-definitions.cmake;1513;set_runtime_outputdirectory;/home/espen/ns-3/ns3-wip/examples/routing/CMakeLists.txt;11;build_example;/home/espen/ns-3/ns3-wip/examples/routing/CMakeLists.txt;0;")
add_test([=[ctest-global-routing-slash32]=] "ns3.36.1-global-routing-slash32-debug")
set_tests_properties([=[ctest-global-routing-slash32]=] PROPERTIES  WORKING_DIRECTORY "/home/espen/ns-3/ns3-wip/build/examples/routing/" _BACKTRACE_TRIPLES "/home/espen/ns-3/ns3-wip/build-support/macros-and-definitions.cmake;1344;add_test;/home/espen/ns-3/ns3-wip/build-support/macros-and-definitions.cmake;1513;set_runtime_outputdirectory;/home/espen/ns-3/ns3-wip/examples/routing/CMakeLists.txt;21;build_example;/home/espen/ns-3/ns3-wip/examples/routing/CMakeLists.txt;0;")
add_test([=[ctest-global-injection-slash32]=] "ns3.36.1-global-injection-slash32-debug")
set_tests_properties([=[ctest-global-injection-slash32]=] PROPERTIES  WORKING_DIRECTORY "/home/espen/ns-3/ns3-wip/build/examples/routing/" _BACKTRACE_TRIPLES "/home/espen/ns-3/ns3-wip/build-support/macros-and-definitions.cmake;1344;add_test;/home/espen/ns-3/ns3-wip/build-support/macros-and-definitions.cmake;1513;set_runtime_outputdirectory;/home/espen/ns-3/ns3-wip/examples/routing/CMakeLists.txt;31;build_example;/home/espen/ns-3/ns3-wip/examples/routing/CMakeLists.txt;0;")
add_test([=[ctest-simple-alternate-routing]=] "ns3.36.1-simple-alternate-routing-debug")
set_tests_properties([=[ctest-simple-alternate-routing]=] PROPERTIES  WORKING_DIRECTORY "/home/espen/ns-3/ns3-wip/build/examples/routing/" _BACKTRACE_TRIPLES "/home/espen/ns-3/ns3-wip/build-support/macros-and-definitions.cmake;1344;add_test;/home/espen/ns-3/ns3-wip/build-support/macros-and-definitions.cmake;1513;set_runtime_outputdirectory;/home/espen/ns-3/ns3-wip/examples/routing/CMakeLists.txt;51;build_example;/home/espen/ns-3/ns3-wip/examples/routing/CMakeLists.txt;0;")
add_test([=[ctest-mixed-global-routing]=] "ns3.36.1-mixed-global-routing-debug")
set_tests_properties([=[ctest-mixed-global-routing]=] PROPERTIES  WORKING_DIRECTORY "/home/espen/ns-3/ns3-wip/build/examples/routing/" _BACKTRACE_TRIPLES "/home/espen/ns-3/ns3-wip/build-support/macros-and-definitions.cmake;1344;add_test;/home/espen/ns-3/ns3-wip/build-support/macros-and-definitions.cmake;1513;set_runtime_outputdirectory;/home/espen/ns-3/ns3-wip/examples/routing/CMakeLists.txt;60;build_example;/home/espen/ns-3/ns3-wip/examples/routing/CMakeLists.txt;0;")
add_test([=[ctest-global-routing-multi-switch-plus-router]=] "ns3.36.1-global-routing-multi-switch-plus-router-debug")
set_tests_properties([=[ctest-global-routing-multi-switch-plus-router]=] PROPERTIES  WORKING_DIRECTORY "/home/espen/ns-3/ns3-wip/build/examples/routing/" _BACKTRACE_TRIPLES "/home/espen/ns-3/ns3-wip/build-support/macros-and-definitions.cmake;1344;add_test;/home/espen/ns-3/ns3-wip/build-support/macros-and-definitions.cmake;1513;set_runtime_outputdirectory;/home/espen/ns-3/ns3-wip/examples/routing/CMakeLists.txt;110;build_example;/home/espen/ns-3/ns3-wip/examples/routing/CMakeLists.txt;0;")
add_test([=[ctest-simple-multicast-flooding]=] "ns3.36.1-simple-multicast-flooding-debug")
set_tests_properties([=[ctest-simple-multicast-flooding]=] PROPERTIES  WORKING_DIRECTORY "/home/espen/ns-3/ns3-wip/build/examples/routing/" _BACKTRACE_TRIPLES "/home/espen/ns-3/ns3-wip/build-support/macros-and-definitions.cmake;1344;add_test;/home/espen/ns-3/ns3-wip/build-support/macros-and-definitions.cmake;1513;set_runtime_outputdirectory;/home/espen/ns-3/ns3-wip/examples/routing/CMakeLists.txt;125;build_example;/home/espen/ns-3/ns3-wip/examples/routing/CMakeLists.txt;0;")
